name: survey_mobile
description: "Survey Right - Offline-first mobile survey data collection app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.3.0
  connectivity_plus: ^6.1.4
  provider: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sqflite_common_ffi: ^2.4.0+2
  sqflite_common_ffi_web: ^0.4.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
